---
categories:
- ""
- ""
date: "2020-10-4"
description: What is going on in the American Society?
draft: false
image: picture03.jpg
keywords: ""
slug: project3
title: General Social Survey (GSS)
---



<div id="general-social-survey-gss" class="section level1">
<h1>General Social Survey (GSS)</h1>
<p>The <a href="http://www.gss.norc.org/">General Social Survey (GSS)</a> gathers data on American society in order to monitor and explain trends in attitudes, behaviours, and attributes. Many trends have been tracked for decades, so one can see the evolution of attitudes, etc in American Society.</p>
<p>In this assignment we analyze data from the <strong>2016 GSS sample data</strong>, using it to estimate values of <em>population parameters</em> of interest about US adults. The GSS sample data file has 2867 observations of 935 variables, but we are only interested in very few of these variables and you are using a smaller file.</p>
<pre class="r"><code>gss &lt;- read_csv(here::here(&quot;data&quot;, &quot;smallgss2016.csv&quot;), 
                na = c(&quot;&quot;, &quot;Don&#39;t know&quot;,
                       &quot;No answer&quot;, &quot;Not applicable&quot;))</code></pre>
<p>You will also notice that many responses should not be taken into consideration, like “No Answer”, “Don’t Know”, “Not applicable”, “Refused to Answer”.</p>
<p>We will be creating 95% confidence intervals for population parameters. The variables we have are the following:</p>
<ul>
<li>hours and minutes spent on email weekly. The responses to these questions are recorded in the <code>emailhr</code> and <code>emailmin</code> variables. For example, if the response is 2.50 hours, this would be recorded as emailhr = 2 and emailmin = 30.</li>
<li><code>snapchat</code>, <code>instagrm</code>, <code>twitter</code>: whether respondents used these social media in 2016</li>
<li><code>sex</code>: Female - Male</li>
<li><code>degree</code>: highest education level attained</li>
</ul>
<div id="instagram-and-snapchat-by-sex" class="section level2">
<h2>Instagram and Snapchat, by sex</h2>
<p>Can we estimate the <em>population</em> proportion of Snapchat or Instagram users in 2016?</p>
<ol style="list-style-type: decimal">
<li>Create a new variable, <code>snap_insta</code> that is <em>Yes</em> if the respondent reported using any of Snapchat (<code>snapchat</code>) or Instagram (<code>instagrm</code>), and <em>No</em> if not. If the recorded value was NA for both of these questions, the value in your new variable should also be NA.</li>
</ol>
<pre class="r"><code>gss&lt;-gss %&gt;%
mutate (snap_insta=if_else(snapchat==&quot;Yes&quot; | instagrm==&quot;Yes&quot;,&quot;Yes&quot;,if_else(snapchat==&quot;NA&quot; &amp;                                     instagrm==&quot;NA&quot;,&quot;NA&quot;,&quot;No&quot;)))</code></pre>
<ol style="list-style-type: decimal">
<li>Calculate the proportion of Yes’s for <code>snap_insta</code> among those who answered the question, i.e. excluding NAs.</li>
</ol>
<pre class="r"><code>gss %&gt;%
summarise(prop_yes=count(snap_insta == &quot;Yes&quot;)/
count(snap_insta, na.rm ==TRUE))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   prop_yes
##      &lt;dbl&gt;
## 1    0.344</code></pre>
<ol style="list-style-type: decimal">
<li>Using the CI formula for proportions, please construct 95% CIs for men and women who used either Snapchat or Instagram</li>
</ol>
<pre class="r"><code>gender_formula_ci&lt;-gss %&gt;%
group_by(sex) %&gt;%
summarise(prop_yes = count(snap_insta == &quot;Yes&quot;)/
count(snap_insta, na.rm ==TRUE),
count = count(snap_insta, na.rm ==TRUE),
se_snap_insta = sqrt(prop_yes*(1-prop_yes)/count),
t_critical = qt(0.95, count - 1),
lower_bound = prop_yes - t_critical * se_snap_insta,
upper_bound = prop_yes + t_critical * se_snap_insta)
gender_formula_ci</code></pre>
<pre><code>## # A tibble: 2 x 7
##   sex    prop_yes count se_snap_insta t_critical lower_bound upper_bound
##   &lt;chr&gt;     &lt;dbl&gt; &lt;int&gt;         &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
## 1 Female    0.392   822        0.0170       1.65       0.364       0.420
## 2 Male      0.285   673        0.0174       1.65       0.257       0.314</code></pre>
</div>
<div id="twitter-by-education-level" class="section level2">
<h2>Twitter, by education level</h2>
<p>Can we estimate the <em>population</em> proportion of Twitter users by education level in 2016?.</p>
<p>There are 5 education levels in variable <code>degree</code> which, in ascneding order of years of education, are Lt high school, High School, Junior college, Bachelor, Graduate.</p>
<ol style="list-style-type: decimal">
<li>Turn <code>degree</code> from a character variable into a factor variable. Make sure the order is the correct one and that levels are not sorted alphabetically which is what R by default does.</li>
</ol>
<pre class="r"><code>gss$degree&lt;-as.factor(gss$degree)
gss$degree&lt;-ordered(gss$degree,levels=
c(&quot;Lt high school&quot;,&quot;High School&quot;,&quot;Junior college&quot;,
&quot;Bachelor&quot;,&quot;Graduate&quot;))</code></pre>
<ol style="list-style-type: decimal">
<li>Create a new variable, <code>bachelor_graduate</code> that is <em>Yes</em> if the respondent has either a <code>Bachelor</code> or <code>Graduate</code> degree. As before, if the recorded value for either was NA, the value in your new variable should also be NA.</li>
</ol>
<pre class="r"><code>gss &lt;- gss %&gt;%
  mutate(bachelor_graduate = case_when(
  degree == &quot;Bachelor&quot; | degree == &quot;Graduate&quot; ~ &quot;Yes&quot;,
  degree == &quot;Lt high school&quot; &amp; degree == &quot;High School&quot; &amp; 
  degree == &quot;Junior college&quot; ~ &quot;No&quot;,
  TRUE ~ &quot;NA&quot;))</code></pre>
<ol style="list-style-type: decimal">
<li>Calculate the proportion of <code>bachelor_graduate</code> who do (Yes) and who don’t (No) use twitter.</li>
</ol>
<pre class="r"><code>gss %&gt;%
filter(twitter==&quot;Yes&quot;) %&gt;%
summarise(bachelor_yes=count(bachelor_graduate == &quot;Yes&quot;)/
count(bachelor_graduate, na.rm ==TRUE))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   bachelor_yes
##          &lt;dbl&gt;
## 1        0.809</code></pre>
<pre class="r"><code>gss %&gt;%
filter(twitter==&quot;No&quot;) %&gt;%
summarise(bachelor_yes=count(bachelor_graduate == &quot;Yes&quot;)/
count(bachelor_graduate, na.rm ==TRUE))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   bachelor_yes
##          &lt;dbl&gt;
## 1        0.505</code></pre>
<ol style="list-style-type: decimal">
<li>Using the CI formula for proportions, please construct two 95% CIs for <code>bachelor_graduate</code> vs whether they use (Yes) and don’t (No) use twitter.</li>
</ol>
<pre class="r"><code>degree_formula_ci_Yes&lt;-gss %&gt;%
filter(twitter==&quot;Yes&quot;) %&gt;%
summarise(prop_yes2 = count(bachelor_graduate == &quot;Yes&quot;)/
count(bachelor_graduate, na.rm ==TRUE),
count2 = count(bachelor_graduate, na.rm ==TRUE),
se_bachelor = sqrt(prop_yes2*(1-prop_yes2)/count2),
t_critical2 = qt(0.95, count2 - 1),
lower_bound = prop_yes2 - t_critical2 * se_bachelor,
upper_bound = prop_yes2 + t_critical2 * se_bachelor)
degree_formula_ci_Yes</code></pre>
<pre><code>## # A tibble: 1 x 6
##   prop_yes2 count2 se_bachelor t_critical2 lower_bound upper_bound
##       &lt;dbl&gt;  &lt;int&gt;       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
## 1     0.809    141      0.0331        1.66       0.754       0.863</code></pre>
<pre class="r"><code>degree_formula_ci_No&lt;-gss %&gt;%
filter(twitter==&quot;No&quot;) %&gt;%
summarise(prop_yes3 = count(bachelor_graduate == &quot;Yes&quot;)/
count(bachelor_graduate, na.rm ==TRUE),
count3 = count(bachelor_graduate, na.rm ==TRUE),
se_bachelor = sqrt(prop_yes3*(1-prop_yes3)/count3),
t_critical3 = qt(0.95, count3 - 1),
lower_bound = prop_yes3 - t_critical3 * se_bachelor,
upper_bound = prop_yes3 + t_critical3 * se_bachelor)
degree_formula_ci_No</code></pre>
<pre><code>## # A tibble: 1 x 6
##   prop_yes3 count3 se_bachelor t_critical3 lower_bound upper_bound
##       &lt;dbl&gt;  &lt;int&gt;       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
## 1     0.505    742      0.0184        1.65       0.475       0.536</code></pre>
<ol style="list-style-type: decimal">
<li>Do these two Confidence Intervals overlap?</li>
</ol>
<blockquote>
<p>The two Confidence Intervals don’t overlap.</p>
</blockquote>
</div>
<div id="email-usage" class="section level2">
<h2>Email usage</h2>
<p>Can we estimate the <em>population</em> parameter on time spent on email weekly?</p>
<ol style="list-style-type: decimal">
<li>Create a new variable called <code>email</code> that combines <code>emailhr</code> and <code>emailmin</code> to reports the number of minutes the respondents spend on email weekly.</li>
</ol>
<pre class="r"><code> gss&lt;-gss%&gt;%
 mutate(emailhr=as.numeric(emailhr))
 gss&lt;-gss%&gt;%
 mutate(emailmin=as.numeric(emailmin))
 gss &lt;-gss %&gt;%
 mutate(email=case_when(
 emailhr == &quot;NA&quot; | emailmin == &quot;NA&quot; ~ &quot;NA&quot;,
 TRUE ~ as.character(emailhr*60+emailmin)))
 gss&lt;-drop_na(gss,email)
 gss&lt;-gss%&gt;%
 mutate(email=as.numeric(email))</code></pre>
<ol style="list-style-type: decimal">
<li>Visualise the distribution of this new variable. Find the mean and the median number of minutes respondents spend on email weekly. Is the mean or the median a better measure of the typical amount of time Americans spend on email weekly? Why?</li>
</ol>
<pre class="r"><code>ggplot(gss,mapping=aes(x=email))+
geom_histogram(binwidth=50)+
labs(title=&quot;the Histogram Distribution of Email Time&quot;,x=&quot;email time&quot;)</code></pre>
<p><img src="/projects/project3_files/figure-html/distribution_email-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>gss&lt;-gss%&gt;%
mutate(email=as.numeric(email))
summarise(gss,avg_email=mean(email,na.rm=TRUE),
med_email=median(email,na.rm=TRUE),count_email=count(email&gt;1000))</code></pre>
<pre><code>## # A tibble: 1 x 3
##   avg_email med_email count_email
##       &lt;dbl&gt;     &lt;dbl&gt;       &lt;int&gt;
## 1      417.       120         221</code></pre>
<pre class="r"><code>skim(gss$email)</code></pre>
<table>
<caption>(#tab:distribution_email)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">gss$email</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">1649</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">data</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">417</td>
<td align="right">680</td>
<td align="right">0</td>
<td align="right">50</td>
<td align="right">120</td>
<td align="right">480</td>
<td align="right">6000</td>
<td align="left">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
<blockquote>
<p>The median is a better measure of the typical amount of time Americans spend on email weekly,because the graph is right-skewed and in the distribution there are a large amount of big values.For instance, there are 221 out of 1649 (=2867-1218) values that are more than 1000. These values will pull up the mean but the median is not affected.</p>
</blockquote>
<ol style="list-style-type: decimal">
<li>Using the <code>infer</code> package, calculate a 95% bootstrap confidence interval for the mean amount of time Americans spend on email weekly. Interpret this interval in context of the data, reporting its endpoints in “humanized” units (e.g. instead of 108 minutes, report 1 hr and 8 minutes). If you get a result that seems a bit odd, discuss why you think this might be the case.</li>
</ol>
<pre class="r"><code>library(infer)
set.seed(1234)
boot_email&lt;-gss%&gt;%
specify(response=email)%&gt;%
generate(reps=1000,type=&quot;bootstrap&quot;)%&gt;%
calculate(stat=&quot;mean&quot;)
percentile_ci&lt;-boot_email%&gt;%
  get_confidence_interval(level=0.95,type=&quot;percentile&quot;)
percentile_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     385.     453.</code></pre>
<blockquote>
<p>We are 95% confident that the interval (6 hours and 25 minutes, 7 hours and 32 minutes) capture the true mean amount of time Americans spend on email weekly. The thing that is odd is that the 95% confident interval doesn’t include the median. And that is because there are a large amount of extreme values.</p>
</blockquote>
<ol style="list-style-type: decimal">
<li>Would you expect a 99% confidence interval to be wider or narrower than the interval you calculated above? Explain your reasoning.</li>
</ol>
<blockquote>
<p>A 99% confidence interval will be wider bacause a wider CI can make sure that about 99% (a higher percentage) of the CIs generated from the samples capture the true mean value.</p>
</blockquote>
</div>
</div>
