<!DOCTYPE HTML>
<html>

    <head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<meta name="description" content="Pingchuan Tian&#39;s description">
	<meta name="author" content="Pingchuan Tian">
	<meta name="generator" content="Hugo 0.75.1" />
	<title>General Social Survey (GSS) &middot; Pingchuan Tian</title>
	<!-- Stylesheets -->
	
	<link rel="stylesheet" href="/css/main.css"/>
	
	

	

	<!-- Custom Fonts -->
	<link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
	<link rel="icon" type="image/x-icon" href="/favicon.ico">
	

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="js/ie/html5shiv.js"></script>
	<script src="js/ie/html5shiv.jsrespond.min.js"></script>
	<![endif]-->
</head>

    <body>

    <!-- Wrapper -->
        <div id="wrapper">

            <!-- Header -->
    <header id="header" class="alt">
        <a href="/" class="logo"><strong>Forty</strong> <span>By HTML5 Up</span></a>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>

<!-- Menu -->
    <nav id="menu">
        <ul class="links">
            
                <li><a href="/">Home</a></li>
            
                <li><a href="/blogs">Blogs</a></li>
            
                <li><a href="/blogs/ipsum">Generic Blog</a></li>
            
                <li><a href="/elements.html">Elements</a></li>
            

        </ul>
        <ul class="actions vertical">
            
                <li><a href="/blogs" class="button special fit">Get Started</a></li>
            
            
                <li><a href="/" class="button fit">Log In</a></li>
            
        </ul>
    </nav>

        <!-- Main -->
            <div id="main" class="alt">

                
                    <section id="one">
                        <div class="inner">
                            <header class="major">
                                <h1>General Social Survey (GSS)</h1>
                            </header>
                            
                                <span class="image main"><img src="/img/projects/pic07.jpg" alt="" /></span>
                            
                            


<div id="general-social-survey-gss" class="section level1">
<h1>General Social Survey (GSS)</h1>
<p>The <a href="http://www.gss.norc.org/">General Social Survey (GSS)</a> gathers data on American society in order to monitor and explain trends in attitudes, behaviours, and attributes. Many trends have been tracked for decades, so one can see the evolution of attitudes, etc in American Society.</p>
<p>In this assignment we analyze data from the <strong>2016 GSS sample data</strong>, using it to estimate values of <em>population parameters</em> of interest about US adults. The GSS sample data file has 2867 observations of 935 variables, but we are only interested in very few of these variables and you are using a smaller file.</p>
<pre class="r"><code>gss &lt;- read_csv(here::here(&quot;data&quot;, &quot;smallgss2016.csv&quot;), 
                na = c(&quot;&quot;, &quot;Don&#39;t know&quot;,
                       &quot;No answer&quot;, &quot;Not applicable&quot;))</code></pre>
<p>You will also notice that many responses should not be taken into consideration, like “No Answer”, “Don’t Know”, “Not applicable”, “Refused to Answer”.</p>
<p>We will be creating 95% confidence intervals for population parameters. The variables we have are the following:</p>
<ul>
<li>hours and minutes spent on email weekly. The responses to these questions are recorded in the <code>emailhr</code> and <code>emailmin</code> variables. For example, if the response is 2.50 hours, this would be recorded as emailhr = 2 and emailmin = 30.</li>
<li><code>snapchat</code>, <code>instagrm</code>, <code>twitter</code>: whether respondents used these social media in 2016</li>
<li><code>sex</code>: Female - Male</li>
<li><code>degree</code>: highest education level attained</li>
</ul>
<div id="instagram-and-snapchat-by-sex" class="section level2">
<h2>Instagram and Snapchat, by sex</h2>
<p>Can we estimate the <em>population</em> proportion of Snapchat or Instagram users in 2016?</p>
<ol style="list-style-type: decimal">
<li>Create a new variable, <code>snap_insta</code> that is <em>Yes</em> if the respondent reported using any of Snapchat (<code>snapchat</code>) or Instagram (<code>instagrm</code>), and <em>No</em> if not. If the recorded value was NA for both of these questions, the value in your new variable should also be NA.</li>
</ol>
<pre class="r"><code>gss&lt;-gss %&gt;%
mutate (snap_insta=if_else(snapchat==&quot;Yes&quot; | instagrm==&quot;Yes&quot;,&quot;Yes&quot;,if_else(snapchat==&quot;NA&quot; &amp;                                     instagrm==&quot;NA&quot;,&quot;NA&quot;,&quot;No&quot;)))</code></pre>
<ol style="list-style-type: decimal">
<li>Calculate the proportion of Yes’s for <code>snap_insta</code> among those who answered the question, i.e. excluding NAs.</li>
</ol>
<pre class="r"><code>gss %&gt;%
summarise(prop_yes=count(snap_insta == &quot;Yes&quot;)/
count(snap_insta, na.rm ==TRUE))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   prop_yes
##      &lt;dbl&gt;
## 1    0.344</code></pre>
<ol style="list-style-type: decimal">
<li>Using the CI formula for proportions, please construct 95% CIs for men and women who used either Snapchat or Instagram</li>
</ol>
<pre class="r"><code>gender_formula_ci&lt;-gss %&gt;%
group_by(sex) %&gt;%
summarise(prop_yes = count(snap_insta == &quot;Yes&quot;)/
count(snap_insta, na.rm ==TRUE),
count = count(snap_insta, na.rm ==TRUE),
se_snap_insta = sqrt(prop_yes*(1-prop_yes)/count),
t_critical = qt(0.95, count - 1),
lower_bound = prop_yes - t_critical * se_snap_insta,
upper_bound = prop_yes + t_critical * se_snap_insta)
gender_formula_ci</code></pre>
<pre><code>## # A tibble: 2 x 7
##   sex    prop_yes count se_snap_insta t_critical lower_bound upper_bound
##   &lt;chr&gt;     &lt;dbl&gt; &lt;int&gt;         &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
## 1 Female    0.392   822        0.0170       1.65       0.364       0.420
## 2 Male      0.285   673        0.0174       1.65       0.257       0.314</code></pre>
</div>
<div id="twitter-by-education-level" class="section level2">
<h2>Twitter, by education level</h2>
<p>Can we estimate the <em>population</em> proportion of Twitter users by education level in 2016?.</p>
<p>There are 5 education levels in variable <code>degree</code> which, in ascneding order of years of education, are Lt high school, High School, Junior college, Bachelor, Graduate.</p>
<ol style="list-style-type: decimal">
<li>Turn <code>degree</code> from a character variable into a factor variable. Make sure the order is the correct one and that levels are not sorted alphabetically which is what R by default does.</li>
</ol>
<pre class="r"><code>gss$degree&lt;-as.factor(gss$degree)
gss$degree&lt;-ordered(gss$degree,levels=
c(&quot;Lt high school&quot;,&quot;High School&quot;,&quot;Junior college&quot;,
&quot;Bachelor&quot;,&quot;Graduate&quot;))</code></pre>
<ol style="list-style-type: decimal">
<li>Create a new variable, <code>bachelor_graduate</code> that is <em>Yes</em> if the respondent has either a <code>Bachelor</code> or <code>Graduate</code> degree. As before, if the recorded value for either was NA, the value in your new variable should also be NA.</li>
</ol>
<pre class="r"><code>gss &lt;- gss %&gt;%
  mutate(bachelor_graduate = case_when(
  degree == &quot;Bachelor&quot; | degree == &quot;Graduate&quot; ~ &quot;Yes&quot;,
  degree == &quot;Lt high school&quot; &amp; degree == &quot;High School&quot; &amp; 
  degree == &quot;Junior college&quot; ~ &quot;No&quot;,
  TRUE ~ &quot;NA&quot;))</code></pre>
<ol style="list-style-type: decimal">
<li>Calculate the proportion of <code>bachelor_graduate</code> who do (Yes) and who don’t (No) use twitter.</li>
</ol>
<pre class="r"><code>gss %&gt;%
filter(twitter==&quot;Yes&quot;) %&gt;%
summarise(bachelor_yes=count(bachelor_graduate == &quot;Yes&quot;)/
count(bachelor_graduate, na.rm ==TRUE))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   bachelor_yes
##          &lt;dbl&gt;
## 1        0.809</code></pre>
<pre class="r"><code>gss %&gt;%
filter(twitter==&quot;No&quot;) %&gt;%
summarise(bachelor_yes=count(bachelor_graduate == &quot;Yes&quot;)/
count(bachelor_graduate, na.rm ==TRUE))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   bachelor_yes
##          &lt;dbl&gt;
## 1        0.505</code></pre>
<ol style="list-style-type: decimal">
<li>Using the CI formula for proportions, please construct two 95% CIs for <code>bachelor_graduate</code> vs whether they use (Yes) and don’t (No) use twitter.</li>
</ol>
<pre class="r"><code>degree_formula_ci_Yes&lt;-gss %&gt;%
filter(twitter==&quot;Yes&quot;) %&gt;%
summarise(prop_yes2 = count(bachelor_graduate == &quot;Yes&quot;)/
count(bachelor_graduate, na.rm ==TRUE),
count2 = count(bachelor_graduate, na.rm ==TRUE),
se_bachelor = sqrt(prop_yes2*(1-prop_yes2)/count2),
t_critical2 = qt(0.95, count2 - 1),
lower_bound = prop_yes2 - t_critical2 * se_bachelor,
upper_bound = prop_yes2 + t_critical2 * se_bachelor)
degree_formula_ci_Yes</code></pre>
<pre><code>## # A tibble: 1 x 6
##   prop_yes2 count2 se_bachelor t_critical2 lower_bound upper_bound
##       &lt;dbl&gt;  &lt;int&gt;       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
## 1     0.809    141      0.0331        1.66       0.754       0.863</code></pre>
<pre class="r"><code>degree_formula_ci_No&lt;-gss %&gt;%
filter(twitter==&quot;No&quot;) %&gt;%
summarise(prop_yes3 = count(bachelor_graduate == &quot;Yes&quot;)/
count(bachelor_graduate, na.rm ==TRUE),
count3 = count(bachelor_graduate, na.rm ==TRUE),
se_bachelor = sqrt(prop_yes3*(1-prop_yes3)/count3),
t_critical3 = qt(0.95, count3 - 1),
lower_bound = prop_yes3 - t_critical3 * se_bachelor,
upper_bound = prop_yes3 + t_critical3 * se_bachelor)
degree_formula_ci_No</code></pre>
<pre><code>## # A tibble: 1 x 6
##   prop_yes3 count3 se_bachelor t_critical3 lower_bound upper_bound
##       &lt;dbl&gt;  &lt;int&gt;       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
## 1     0.505    742      0.0184        1.65       0.475       0.536</code></pre>
<ol style="list-style-type: decimal">
<li>Do these two Confidence Intervals overlap?</li>
</ol>
<blockquote>
<p>The two Confidence Intervals don’t overlap.</p>
</blockquote>
</div>
<div id="email-usage" class="section level2">
<h2>Email usage</h2>
<p>Can we estimate the <em>population</em> parameter on time spent on email weekly?</p>
<ol style="list-style-type: decimal">
<li>Create a new variable called <code>email</code> that combines <code>emailhr</code> and <code>emailmin</code> to reports the number of minutes the respondents spend on email weekly.</li>
</ol>
<pre class="r"><code> gss&lt;-gss%&gt;%
 mutate(emailhr=as.numeric(emailhr))
 gss&lt;-gss%&gt;%
 mutate(emailmin=as.numeric(emailmin))
 gss &lt;-gss %&gt;%
 mutate(email=case_when(
 emailhr == &quot;NA&quot; | emailmin == &quot;NA&quot; ~ &quot;NA&quot;,
 TRUE ~ as.character(emailhr*60+emailmin)))</code></pre>
<ol style="list-style-type: decimal">
<li>Visualise the distribution of this new variable. Find the mean and the median number of minutes respondents spend on email weekly. Is the mean or the median a better measure of the typical amount of time Americans spend on email weekly? Why?</li>
</ol>
<pre class="r"><code>as.numeric(gss$email)</code></pre>
<pre><code>##    [1]  720   30   NA   10   NA  120 2400   NA    0   NA  120   NA  600   NA
##   [15]   30   NA   NA   60   60  120 1500   NA   60   NA   NA   NA   NA    0
##   [29]   10   NA   60   NA  120   NA    0   30  300  120   NA   NA   NA   60
##   [43]  420   NA   90   NA 3600  240   NA 1200 2700  120   60   NA    0  420
##   [57]  120 1500   NA   45   NA   20   NA   60   NA   NA 3600   20   NA   NA
##   [71]    0 2640   NA   60   60   NA  900  600   NA   NA 2400   NA  120   NA
##   [85]   NA  120 3600   NA   NA   NA  300   NA  300   NA   NA  900   60  600
##   [99]   NA   NA   NA    0   NA   NA   NA   NA   NA   NA  300   NA  180   NA
##  [113]   NA  120  240   NA   NA   45   NA  420   60   NA   NA 3000   60   60
##  [127]  600   NA 1200 2400   NA 1200   NA  210   NA   60   NA   NA  480   NA
##  [141]   60   NA   60   NA   10 1800   NA   30 3000  120   NA  300   NA 1200
##  [155]   NA   60   NA  180 2400    0  300  600   NA   NA   NA   NA   NA  420
##  [169]   NA   NA   60   NA   15   NA   60 1800 1200   NA   NA   60   NA   60
##  [183]   NA   60   NA   60   NA  480    0   NA   NA    0   NA   60  240 1500
##  [197]   NA  240   60  720 2520  120  300  600   NA  300  600   NA   30  240
##  [211]  720  120   20   NA  120   NA   60    0  480   NA   NA   NA   NA   NA
##  [225]  480  300   NA  300   NA  300  120   NA  480   NA  120 1200   NA   NA
##  [239]   60    2   10   10    0   60  420   60   NA  600 1200   NA  480   60
##  [253]   NA  120   NA  120  120   60   NA 5400  600   NA  120 4500  300   60
##  [267]   60    0   NA   10   NA  300   60 1500  360   NA  100   NA  600  480
##  [281]  120   60   NA  600    0   NA  180   NA  120  600 1200 1320 1200  180
##  [295]   NA    0   60   NA 1200  180  180   NA   60    0 3000  600   20  120
##  [309]  180   15 3000  180   NA  300   NA  720  900  120    0  120   NA  720
##  [323]  900    0   NA    0   NA    0  900  900   NA  600  180   60   NA  480
##  [337]   NA    5   60   10   NA   30   NA  180   NA  120  120 2400  180   59
##  [351]   NA    1  720  600   NA   NA   NA  720   NA 1500   NA 1440   30   NA
##  [365] 1920  600   NA  120  300   NA   NA   60   NA   NA   NA  600   NA 1260
##  [379]   NA  360  180  600  360   NA 1800  600   NA 1200   NA  480   NA   NA
##  [393]   NA  600   NA   30   NA  600 1800 1320   NA  180   NA   NA  720   NA
##  [407]  420  420 1800  120  150   NA 2400 1800   NA   NA  900   NA    0   NA
##  [421]  420   NA  750   NA  300   NA  600 1200  120   NA   NA 3000   NA   NA
##  [435]   NA  600    0 1680    0   20   NA 1200   NA   NA    5  180    0   20
##  [449] 1500  420   70   NA  420  120  600   NA 3360   NA 2100  600   NA 1200
##  [463]   NA  120   NA  120  600   NA   60  600   NA  240   60   60   NA    0
##  [477]    0   60  180   NA  120   NA   NA  720 1200   NA   NA  240   NA   NA
##  [491]   NA   NA    0   NA  240    0 2700 2400   NA  420  120   NA   NA   NA
##  [505]   30  840   NA  180  720   NA    2   70   NA    5   NA  120 3600   NA
##  [519]   20   30 1200   60  420 1200  150  420   60   NA  600 1800   NA   NA
##  [533]  300   NA    0   40   NA   NA   NA   10 1200   NA  240  600   NA   60
##  [547]   NA  120   NA   NA  480   NA   NA   60   NA  120  360  600   NA   NA
##  [561]   NA   NA   NA   NA   NA    0   NA  120   60   NA    2  240  180  600
##  [575]   NA  120   NA   NA    0   60   NA   NA   60   NA   60   NA   NA   NA
##  [589]  180  300   NA   NA 3600  600   NA   NA  600   NA  480  900   NA    0
##  [603]    0   NA   NA  600  600   NA  120 1920   20   60   NA   NA   NA  300
##  [617]  300  600   NA  180   30   NA   60   NA    0   NA   60  600   60   NA
##  [631]    1   NA  720  180  180  300   NA  180   NA   60   NA   30 1800  600
##  [645]   NA   NA   NA  240   NA  540    0  600   10  480   NA   NA   NA   NA
##  [659]   60   60   NA   NA 1200   NA  420   NA    0   60   NA    5   NA   20
##  [673]   NA    2 1800   NA  900 1320   NA   60   NA   NA   NA    0   NA   NA
##  [687]  300   NA   NA   NA  480   NA    0    0   NA   NA   60   60   NA   NA
##  [701]  420  300  240   30 1260  600   NA   NA  300    0   NA   NA  120   NA
##  [715]   60  120   NA    0 1200   NA  480   NA   NA   NA   NA  480   NA   NA
##  [729]   60  120 1215   NA   NA  300   NA   60  600   NA    0   NA  120  360
##  [743]   NA   90  360   NA  120   NA   60 2700   NA  300   60   NA   NA   NA
##  [757]   NA 1320   NA   60  120  120   NA   NA    0   NA   60  240   NA 1200
##  [771]   NA   NA 1200  120   NA    0   NA   60   NA   NA   NA  180    0 1200
##  [785]   90 4200   NA 1200   NA  180   NA    2    0   NA   60   25   NA   60
##  [799]   NA   60   NA  240  180   30   60    0 3000   70   60   NA  300 1200
##  [813]   NA 1200   NA  120    0  360   NA  600   NA  840   NA   NA  480   NA
##  [827]   60   20   NA   90   NA   NA    0   NA 1800  120   NA   NA   NA  300
##  [841]   NA   NA   NA   60   20  360 2400   NA 3000  180   NA  600    0   NA
##  [855]   40   NA   30   NA  900   NA  600   NA   NA   60   15   NA    0   NA
##  [869]   NA   NA  300    0   NA   NA 1200   NA   NA   30  120    0 1200   45
##  [883]  900   NA 1500   NA  480   NA 1500  300  120   NA   60   NA   30   NA
##  [897]   NA  240   10  600  600   NA  720   NA    0  120   60  600   NA   NA
##  [911]   NA   60  120    0  180   NA   60   NA   NA  300   NA   60 1200   70
##  [925]  300 1200   NA   NA    0 1800   NA   60   NA    0   NA    0   NA 1800
##  [939]  600  420 2400   60   NA   60   NA   NA   NA   NA 2400   NA   NA 2100
##  [953]   NA  120   NA   NA   NA   NA   NA   NA   NA  120    0   60   NA    0
##  [967]   30   30   NA   30   NA   NA   NA   60   60   NA  180   NA   NA  720
##  [981]   30   NA  300   NA 1800   NA   NA   NA   30   NA   NA  180  180 1800
##  [995]   NA  900  600  240   NA  240   NA    0   60   30   60  360   NA  900
## [1009]   60  300   60   NA  120  900   NA  240 2820   NA 2400   NA  480   30
## [1023]   90   NA  720  480 1200   60  120   NA  600  900 1200  900   NA  600
## [1037]   NA  300   60   60  120  120  120   NA  900   NA   90  510   60   NA
## [1051]   NA 1020  120   NA  120   NA 1800    0   NA  420  600   60   NA   NA
## [1065]   NA    0   NA   NA  120   NA  480    0  120   NA   NA    0   NA   NA
## [1079]   NA   60  120   30 2400   NA    0   NA   60   20   NA   30   NA  120
## [1093]    0   60   NA  900   NA   60  570   NA  180   10   30   NA   NA  300
## [1107]  120   60   NA   90    0   NA   NA   NA   NA  150  420   NA  120  240
## [1121]    0 1200   NA  120   60   NA   60   10   NA 2400   NA  180   15   NA
## [1135]   60   60   NA  105   NA   15   20   NA   60  120   NA   60   NA   20
## [1149]  240 1500   NA  300   NA   60   NA 2400 2400   NA  120   NA  420  840
## [1163]   NA  300  600   NA   60   NA  120  900   NA   NA   60   NA    5    0
## [1177]  720  360   NA   60   NA  900    0   NA   NA   NA   NA   NA   10   NA
## [1191]   60   NA  480  840   NA   NA  600   NA   90   NA   NA   NA   15   NA
## [1205]  120    1   NA    5   30    0 1200    0   NA   NA  600   10   NA    0
## [1219] 1500  360   NA  120    0 1200  120   NA    1   NA   60   NA   60   NA
## [1233]    0   NA   90   NA   NA   60   60 2100   NA  120   NA 1200   NA   NA
## [1247]   90   NA   NA  600 1200   60  240   NA   45 1500  180 2100    0   NA
## [1261]    0   NA   NA   NA 4200   NA   60   NA   60   NA   NA  300   NA 2880
## [1275]   NA   NA    0   NA   60 1680   NA  360   NA   NA 1200   60   NA   NA
## [1289]    0    0   30 1200   NA   60   NA 1500  420 2400   60   60   NA  120
## [1303]   NA   NA   NA   NA  420   NA   NA   60   NA  180   NA   NA   NA   NA
## [1317]   NA   60   NA   NA   NA  180   NA 1800   NA   90   NA 1200  900   NA
## [1331]  180   NA 1200   NA   NA    0   NA 1200   NA  600   30   NA   30 1200
## [1345]   60  360   NA  240   NA   NA   15   NA  240   60   NA    0    0   NA
## [1359]   NA   30   NA  600  120  120   NA   30   NA   NA   60   20   60   15
## [1373]   60   NA  720  120   NA  120   NA  420   10   NA  300   60   NA   20
## [1387]   15   NA   NA    0   NA  240   NA 1200   NA 1800  120   NA   30    0
## [1401]   60   NA 2400   NA  960   NA   NA  180   NA    0   NA  600   NA   NA
## [1415]  900   60   NA   60  120   50 2400   NA    0   NA 1200  300   NA  240
## [1429]  900  600  180  120   NA   NA   NA   25   NA   NA  180  300   NA   NA
## [1443]  300   NA  120  600   NA    0   NA   NA   NA  480   NA   NA 1200  120
## [1457]  900   NA  120  300   20    2   NA    0   NA   NA   NA   NA   60   60
## [1471]   60  120  180  180   NA   NA  600   NA  120  480  360  300    0   NA
## [1485]   48   NA  420   NA   NA   NA 3000 3000 1500   NA 1800  180   NA    0
## [1499]  120   NA 1800   NA 1500  480   60   NA   NA   NA   15   NA   NA   10
## [1513]   NA   NA  180    0   NA   NA   10   NA   60   NA  360  120   NA   NA
## [1527]  360    0   NA   NA 1200   NA  120    0   60  300   NA  120  180   NA
## [1541]  300   NA  240   60   60  120   NA  120   NA    0  420 2400   30   NA
## [1555]   10  120   NA   NA   NA  900   NA   60   NA  720 1800   NA  420   NA
## [1569]  300   NA  600 1200   NA   NA  900   NA   NA   NA   NA   NA  300   20
## [1583]   NA 3600  120    0   NA   NA   60   10   NA  420   30   NA   NA   NA
## [1597]   NA  120   NA   60   NA  180   NA  120   NA   NA  480   NA   NA  240
## [1611] 3000   NA   40 1500   NA    0   NA 2100   10   NA 2700   NA   30   60
## [1625]   NA   NA   NA  120   60   60    0   NA    0   NA  420   NA  300    2
## [1639]   NA    0   NA   60    0   60  360  900   60   NA   NA   30   NA   NA
## [1653]   NA   60   NA   NA    0   NA  420    0    0  120  600   NA  120   NA
## [1667]  210   NA   NA  300   NA  180  840   NA    0   NA   30   NA    0   NA
## [1681]    0   60  120   NA  120   NA   NA   90  120   NA 2100  480   NA   NA
## [1695]    0   30   NA   60   NA   NA    0   60   NA   60   NA 2400   60    0
## [1709]   60   60  600   NA  240    0   NA  120  120   NA   NA   NA   NA   60
## [1723]    0   NA  900   NA  120   60  120   NA    0   NA   NA   NA  300  120
## [1737]  540 1500   NA  120   NA   90  120   NA 1800 1800  120   60   NA 1200
## [1751]  120   NA 2400   NA   NA   NA    0  360   NA   NA  240   NA  300   NA
## [1765]   NA   NA   NA   NA   NA   NA   NA   60   NA  120  360   60   NA    0
## [1779] 1200   NA   NA  120   NA   60    0  180   30   NA    0   60   NA  900
## [1793]  600  120   NA  180  240  360   NA    0  120  600   NA   NA  300   20
## [1807]   NA 1200   NA  180   NA   NA   NA 1500   NA  120   60  240   NA  210
## [1821]   NA   90   60   NA   NA   60 1800   NA  600   NA   NA  240   NA   30
## [1835]  600   60   NA   NA   60  240    0   NA  600   NA    0  120   NA 2400
## [1849]   60   NA   NA  300  600   60  420   NA   NA   60   NA   NA   NA  120
## [1863]   NA   60   30   NA   NA    0   NA   40   NA   NA    0   NA   45  480
## [1877]   NA   NA    0 1200   NA   NA  150   NA  840   NA   NA    0  480  120
## [1891]   NA   15   30   60   30   NA  180  300   NA 1320  180   NA   NA 1200
## [1905]    0  300  120   30   NA  420   NA   NA   60   NA  120   NA  180   NA
## [1919]  720   NA   60   NA   NA   NA   NA    0   NA   60 1200   60   NA   30
## [1933]   NA  360   60  420  720   NA   60   NA   NA  600 1800   NA   NA   NA
## [1947]  600   NA  480   NA   NA  600  120  120   NA  180   NA    0   NA  600
## [1961]   60   NA   60   60   60   NA  420   NA 2100   NA  300  480   NA    0
## [1975]   NA   NA   60   60   NA   NA   NA   60  300  120   NA   10  120  300
## [1989]   60    0   NA   60   NA  120   NA    0   NA 1500   NA   60   30   NA
## [2003]   30   30   NA    0   NA 2100  600   60  120  120   60    0  300   20
## [2017]   NA   60    0  120   NA   NA   60    0   NA   60   NA   NA   NA    5
## [2031]   NA   60   NA   NA  120   NA  120    0  240  840  240   NA  180  480
## [2045]   NA   NA  960   NA   NA   60   NA   NA    0   NA  300 2160  240   NA
## [2059] 1200   NA   30   60   NA   NA   60   NA   NA    0   45  180  240   NA
## [2073]  300   NA   NA    0    0   NA 1200   NA    0   NA   60  300   NA  120
## [2087]   NA  900   NA   60  600   NA   30   NA   60  240   NA  180   NA  120
## [2101]   NA  120  360    0   60   NA  300   NA   NA   30   NA   30  180   NA
## [2115]  240   NA 1500  300   NA  120 1200 3000   NA   NA 1200   NA  240 1500
## [2129]  420  600   NA   NA   NA  180  120   NA  300 1200   NA   60   NA  480
## [2143]  120  300   NA   60 4320    0   NA    0   NA    0  180  120    0    0
## [2157]   30   NA  180   NA    0   60   60   NA   NA    0   NA 1200   NA    0
## [2171]   NA   NA   NA   NA   NA 1800  480   30   NA   NA  540   NA   60  360
## [2185]   NA  120 1200  600   NA  300   NA  600   NA   20  420   NA   60   NA
## [2199]  900   10 1260  600  840   NA  180  240  240   NA   NA   30   NA   NA
## [2213]    0   NA   NA   60   NA    1  480   NA   NA  420   NA   90  600   NA
## [2227]  480   NA   30   NA  720  120   NA  300   NA   NA   30   NA  480   NA
## [2241]   30  420   NA  600  300  120   NA   NA   NA   NA  180   60   NA   NA
## [2255]   NA   NA    0    0   NA   30  420    0   60   NA   60   NA   30  600
## [2269]   NA   NA    0  120   NA  600   NA    0 1200    0  300   NA  240   60
## [2283] 1800   NA    0   NA    0   NA 1260   NA    0   NA   NA  180   NA   NA
## [2297]  240  240  120   30   NA   NA   60   NA   NA 2400  120  180   NA   NA
## [2311]    0 1200   50   NA  240   10   30   NA  420   30  120  240  360   60
## [2325]   NA 1800   60   NA   NA   NA   NA   NA  180   NA   NA   60  600   NA
## [2339] 1800   60  120   NA    0   60   NA  240   NA  120  300  240   NA 3000
## [2353]   NA 1500 3600   NA   NA  120   60   NA   NA  900 6000   NA 1200   NA
## [2367]    0 1200   NA   30   NA    0  600    0   NA   NA   20   60    0 1200
## [2381]   NA   NA  300   NA   NA   NA   NA   60   NA    0   NA   30  600    0
## [2395]   NA   30   10   60 1260   NA  180   NA    0   NA   60 1500   NA  300
## [2409]  120   60  180   NA   60   30  300   NA   60   NA   60    0   60   NA
## [2423]   NA 2880   30   NA   NA 1800  300   NA 1200   NA    0  120    0    5
## [2437]  300   60   NA   30   NA  180   60   NA   NA   NA  180  120   60   30
## [2451]   NA    0   60   15  600    0   NA 1200   NA   30   30   NA  240   NA
## [2465]  240   NA  360   NA   60   NA   NA  600   NA   90   NA  120 1200 1500
## [2479]   60   NA  240  120   NA   NA   NA   NA  120   NA   30   NA   NA    0
## [2493]   NA   NA   NA  600   NA    5   60   30  180   NA    5    0   10   NA
## [2507]   15   NA   NA    0   NA   15  120   NA    5    0   NA   20   NA 2520
## [2521]   NA    0  600   NA    2 3000 1200   NA  300   60    0  420   20   NA
## [2535] 1800  600   NA 1500   NA   NA   30   NA   60    0   15  720   60  120
## [2549]    0   NA  360    0   NA   NA   NA   10  120   NA   15   NA  300  900
## [2563]  900   NA   NA   NA   60    0   50   NA   NA  120  240    0   NA   60
## [2577]   60  240   NA  960   NA   60   60    0   NA  120   30  120   NA 1080
## [2591]    0   NA  120   NA   30   NA   NA   45  120 1200   NA    5    0   NA
## [2605]   60   NA  120   NA   60   30   60   NA   NA  180   NA   NA   NA   NA
## [2619]   60    0   NA   60   NA  420   60  120  180  900   NA  480   NA   60
## [2633]  600   NA    0   NA   60   60   NA   60  720   60  240   NA   10   NA
## [2647]   60  420  300   NA 1800   90   NA   60    0   NA  600   NA   NA  300
## [2661]    0   NA   60   NA   NA   NA  120    0  300   NA  120   NA    0   NA
## [2675]   NA   NA   NA   10  840   NA    0    0   NA    0  300  480  300  120
## [2689]   NA    0   NA    0    0   NA  300  600   NA  720  120   NA 1800   NA
## [2703]   NA   NA    0  300 2400   60   NA   60   NA   NA  180   60   NA 1200
## [2717]  420   NA    0  300   NA   NA   10  420   NA   NA   NA  180   NA   NA
## [2731]  720    0    0   NA  900  600   NA   NA   60   60  120   NA   NA   30
## [2745]   NA   NA  300    0   NA   NA   60   NA   NA  240    0    0    0    0
## [2759]   NA   NA   NA   NA  480  240    0    0   20   NA   NA  120   60    0
## [2773]   NA   NA   NA 1800  300   NA   NA   NA   30   90   NA  720  480   NA
## [2787]    0   NA   NA   NA  240   NA   40   NA   10   60   NA   NA   30   NA
## [2801]   60   60   NA   NA   NA  240   NA   NA   NA   NA    0    0   60  150
## [2815]   NA 2400    0  240   NA   NA   NA   NA   60   NA   NA   60   30  120
## [2829]   NA  240   60    0   NA   NA  420   NA  600   NA 1200  480  600   NA
## [2843]   NA   NA  120   NA   NA  300   NA   NA  360   NA 1200  600   NA  300
## [2857]   60  720  240   NA   60   NA 1200  120    0   60   NA</code></pre>
<pre class="r"><code>gss&lt;-drop_na(gss,email)
ggplot(gss,aes(x=email))+
geom_bar(width=1)+
labs(title=&quot;the Histogram Distribution of Email Time&quot;,
x=&quot;email time&quot;)+theme(axis.text.x=element_blank())</code></pre>
<p><img src="/projects/project3_files/figure-html/distribution_email-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>gss&lt;-gss%&gt;%
mutate(email=as.numeric(email))
summarise(gss,avg_email=mean(email,na.rm=TRUE),
med_email=median(email,na.rm=TRUE),count_email=count(email&gt;1000))</code></pre>
<pre><code>## # A tibble: 1 x 3
##   avg_email med_email count_email
##       &lt;dbl&gt;     &lt;dbl&gt;       &lt;int&gt;
## 1      417.       120         221</code></pre>
<pre class="r"><code>skim(gss$email)</code></pre>
<table>
<caption>(#tab:distribution_email)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">gss$email</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">1649</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">data</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">417</td>
<td align="right">680</td>
<td align="right">0</td>
<td align="right">50</td>
<td align="right">120</td>
<td align="right">480</td>
<td align="right">6000</td>
<td align="left">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
<blockquote>
<p>The median is a better measure of the typical amount of time Americans spend on email weekly,because in the distribution there are a large amount of big values.For instance, there are 221 out of 1649 (=2867-1218) values that are more than 1000. These values will pull up the mean but the median is not affected.</p>
</blockquote>
<ol style="list-style-type: decimal">
<li>Using the <code>infer</code> package, calculate a 95% bootstrap confidence interval for the mean amount of time Americans spend on email weekly. Interpret this interval in context of the data, reporting its endpoints in “humanized” units (e.g. instead of 108 minutes, report 1 hr and 8 minutes). If you get a result that seems a bit odd, discuss why you think this might be the case.</li>
</ol>
<pre class="r"><code>library(infer)
set.seed(1234)
boot_email&lt;-gss%&gt;%
specify(response=email)%&gt;%
generate(reps=1000,type=&quot;bootstrap&quot;)%&gt;%
calculate(stat=&quot;mean&quot;)
percentile_ci&lt;-boot_email%&gt;%
  get_confidence_interval(level=0.95,type=&quot;percentile&quot;)
percentile_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     385.     453.</code></pre>
<blockquote>
<p>We are 95% confident that the interval (6 hours and 25 minutes, 7 hours and 32 minutes) capture the true mean amount of time Americans spend on email weekly. The thing that is odd is that the 95% confident interval doesn’t include the median. And that is because there are a large amount of extreme values.</p>
</blockquote>
<ol style="list-style-type: decimal">
<li>Would you expect a 99% confidence interval to be wider or narrower than the interval you calculated above? Explain your reasoning.</li>
</ol>
<blockquote>
<p>A 99% confidence interval will be wider bacause a wider CI can make sure that about 99% (a higher percentage) of the CIs generated from the samples capture the true mean value.</p>
</blockquote>
</div>
</div>

                        </div>
                    </section>
            <!-- Disqus Inject -->
                
            </div>
            
        <!-- Footer -->
            
                <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <ul class="icons">
                
                    <li><a href="https://twitter.com/pB4yxUSTwqc4p8P" class="icon alt fa-twitter" target="_blank"><span class="label">Twitter</span></a></li>
                
                    <li><a href="https://www.facebook.com/pingchuan.tian.5" class="icon alt fa-facebook" target="_blank"><span class="label">Facebook</span></a></li>
                
                    <li><a href="https://www.instagram.com/pingchuan_tian/" class="icon alt fa-instagram" target="_blank"><span class="label">Instagram</span></a></li>
                
                    <li><a href="https://github.com/Pingchuan-Tian" class="icon alt fa-github" target="_blank"><span class="label">GitHub</span></a></li>
                
                    <li><a href="https://www.linkedin.com/in/%E5%B9%B3%E5%B7%9D-%E7%94%B0-19916a184/" class="icon alt fa-linkedin" target="_blank"><span class="label">LinkedIn</span></a></li>
                
            </ul>
            <ul class="copyright">
                <li>&copy; Company Name</li>
                
                <li>Design:  <a href="https://www.html5up.net">HTML5 UP</a></li>
                
            </ul>
        </div>
    </footer>

            
        </div>

    <!-- Scripts -->
        <!-- Scripts -->
    <!-- jQuery -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/jquery.scrolly.min.js"></script>
    <script src="/js/jquery.scrollex.min.js"></script>
    <script src="/js/skel.min.js"></script>
    <script src="/js/util.js"></script>

    

    <!-- Main JS -->
    <script src="/js/main.js"></script>

    

    

    </body>
</html>
