<!DOCTYPE HTML>
<html>

    <head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<meta name="description" content="Pingchuan Tian&#39;s description">
	<meta name="author" content="Pingchuan Tian">
	<meta name="generator" content="Hugo 0.75.1" />
	<title>Analysis of movies- IMDB dataset &middot; Pingchuan Tian</title>
	<!-- Stylesheets -->
	
	<link rel="stylesheet" href="/css/main.css"/>
	
	

	

	<!-- Custom Fonts -->
	<link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
	<link rel="icon" type="image/x-icon" href="/favicon.ico">
	

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="js/ie/html5shiv.js"></script>
	<script src="js/ie/html5shiv.jsrespond.min.js"></script>
	<![endif]-->
</head>

    <body>

    <!-- Wrapper -->
        <div id="wrapper">

            <!-- Header -->
    <header id="header" class="alt">
        <a href="/" class="logo"><strong>Forty</strong> <span>By HTML5 Up</span></a>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>

<!-- Menu -->
    <nav id="menu">
        <ul class="links">
            
                <li><a href="/">Home</a></li>
            
                <li><a href="/blogs">Blogs</a></li>
            
                <li><a href="/blogs/ipsum">Generic Blog</a></li>
            
                <li><a href="/elements.html">Elements</a></li>
            

        </ul>
        <ul class="actions vertical">
            
                <li><a href="/blogs" class="button special fit">Get Started</a></li>
            
            
                <li><a href="/" class="button fit">Log In</a></li>
            
        </ul>
    </nav>

        <!-- Main -->
            <div id="main" class="alt">

                
                    <section id="one">
                        <div class="inner">
                            <header class="major">
                                <h1>Analysis of movies- IMDB dataset</h1>
                            </header>
                            
                                <span class="image main"><img src="/img/projects/picture02.jpg" alt="" /></span>
                            
                            


<div id="analysis-of-movies--imdb-dataset" class="section level1">
<h1>Analysis of movies- IMDB dataset</h1>
<p>We will look at a subset sample of movies, taken from the <a href="https://www.kaggle.com/carolzhangdc/imdb-5000-movie-dataset">Kaggle IMDB 5000 movie dataset</a></p>
<pre class="r"><code>movies &lt;- read_csv(here::here(&quot;data&quot;, &quot;movies.csv&quot;))
glimpse(movies)</code></pre>
<p>Besides the obvious variables of <code>title</code>, <code>genre</code>, <code>director</code>, <code>year</code>, and <code>duration</code>, the rest of the variables are as follows:</p>
<ul>
<li><code>gross</code> : The gross earnings in the US box office, not adjusted for inflation</li>
<li><code>budget</code>: The movie’s budget</li>
<li><code>cast_facebook_likes</code>: the number of facebook likes cast memebrs received</li>
<li><code>votes</code>: the number of people who voted for (or rated) the movie in IMDB</li>
<li><code>reviews</code>: the number of reviews for that movie</li>
<li><code>rating</code>: IMDB average rating</li>
</ul>
<div id="use-your-data-import-inspection-and-cleaning-skills-to-answer-the-following" class="section level2">
<h2>Use your data import, inspection, and cleaning skills to answer the following:</h2>
<ul>
<li>Are there any missing values (NAs)? Are all entries distinct or are there duplicate entries?</li>
</ul>
<pre class="r"><code>movies &lt;- read_csv(here::here(&quot;data&quot;, &quot;movies.csv&quot;))
skim(movies)</code></pre>
<table>
<caption>(#tab:skim_movies)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">movies</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">2961</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">11</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">3</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">8</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">title</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">83</td>
<td align="right">0</td>
<td align="right">2907</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">genre</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">11</td>
<td align="right">0</td>
<td align="right">17</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">director</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">32</td>
<td align="right">0</td>
<td align="right">1366</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table style="width:100%;">
<colgroup>
<col width="18%" />
<col width="9%" />
<col width="12%" />
<col width="8%" />
<col width="8%" />
<col width="6%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">year</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2.00e+03</td>
<td align="right">9.95e+00</td>
<td align="right">1920.0</td>
<td align="right">2.00e+03</td>
<td align="right">2.00e+03</td>
<td align="right">2.01e+03</td>
<td align="right">2.02e+03</td>
<td align="left">▁▁▁▂▇</td>
</tr>
<tr class="even">
<td align="left">duration</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1.10e+02</td>
<td align="right">2.22e+01</td>
<td align="right">37.0</td>
<td align="right">9.50e+01</td>
<td align="right">1.06e+02</td>
<td align="right">1.19e+02</td>
<td align="right">3.30e+02</td>
<td align="left">▃▇▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">gross</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5.81e+07</td>
<td align="right">7.25e+07</td>
<td align="right">703.0</td>
<td align="right">1.23e+07</td>
<td align="right">3.47e+07</td>
<td align="right">7.56e+07</td>
<td align="right">7.61e+08</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">budget</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4.06e+07</td>
<td align="right">4.37e+07</td>
<td align="right">218.0</td>
<td align="right">1.10e+07</td>
<td align="right">2.60e+07</td>
<td align="right">5.50e+07</td>
<td align="right">3.00e+08</td>
<td align="left">▇▂▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">cast_facebook_likes</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1.24e+04</td>
<td align="right">2.05e+04</td>
<td align="right">0.0</td>
<td align="right">2.24e+03</td>
<td align="right">4.60e+03</td>
<td align="right">1.69e+04</td>
<td align="right">6.57e+05</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">votes</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1.09e+05</td>
<td align="right">1.58e+05</td>
<td align="right">5.0</td>
<td align="right">1.99e+04</td>
<td align="right">5.57e+04</td>
<td align="right">1.33e+05</td>
<td align="right">1.69e+06</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">reviews</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5.03e+02</td>
<td align="right">4.94e+02</td>
<td align="right">2.0</td>
<td align="right">1.99e+02</td>
<td align="right">3.64e+02</td>
<td align="right">6.31e+02</td>
<td align="right">5.31e+03</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">rating</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">6.39e+00</td>
<td align="right">1.05e+00</td>
<td align="right">1.6</td>
<td align="right">5.80e+00</td>
<td align="right">6.50e+00</td>
<td align="right">7.10e+00</td>
<td align="right">9.30e+00</td>
<td align="left">▁▁▆▇▁</td>
</tr>
</tbody>
</table>
<blockquote>
<p>There are no missing values. And there are duplicate entries, because there are 2907 distinct titles, but there are 2961 rows in total.</p>
</blockquote>
<ul>
<li>Produce a table with the count of movies by genre, ranked in descending order</li>
</ul>
<pre class="r"><code>movies &lt;- read_csv(here::here(&quot;data&quot;, &quot;movies.csv&quot;))
movies_1&lt;-movies%&gt;%
group_by(genre)%&gt;%
count()
arrange(movies_1,desc(n))</code></pre>
<pre><code>## # A tibble: 17 x 2
## # Groups:   genre [17]
##    genre           n
##    &lt;chr&gt;       &lt;int&gt;
##  1 Comedy        848
##  2 Action        738
##  3 Drama         498
##  4 Adventure     288
##  5 Crime         202
##  6 Biography     135
##  7 Horror        131
##  8 Animation      35
##  9 Fantasy        28
## 10 Documentary    25
## 11 Mystery        16
## 12 Sci-Fi          7
## 13 Family          3
## 14 Musical         2
## 15 Romance         2
## 16 Western         2
## 17 Thriller        1</code></pre>
<ul>
<li>Produce a table with the average gross earning and budget (<code>gross</code> and <code>budget</code>) by genre. Calculate a variable <code>return_on_budget</code> which shows how many $ did a movie make at the box office for each $ of its budget. Ranked genres by this <code>return_on_budget</code> in descending order</li>
</ul>
<pre class="r"><code>movies &lt;- read_csv(here::here(&quot;data&quot;, &quot;movies.csv&quot;))
movies_2&lt;-movies%&gt;%
group_by(genre)
summarise(movies_2,avg_gross=mean(gross),avg_budget=mean(budget))</code></pre>
<pre><code>## # A tibble: 17 x 3
##    genre        avg_gross avg_budget
##    &lt;chr&gt;            &lt;dbl&gt;      &lt;dbl&gt;
##  1 Action       86583860.  71354888.
##  2 Adventure    95794257.  66290069.
##  3 Animation    98433792.  61701429.
##  4 Biography    45201805.  28543696.
##  5 Comedy       42630552.  24446319.
##  6 Crime        37502397.  26596169.
##  7 Documentary  17353973.   5887852.
##  8 Drama        37465371.  26242933.
##  9 Family      149160478.  14833333.
## 10 Fantasy      42408841.  17582143.
## 11 Horror       37713738.  13504916.
## 12 Musical      92084000    3189500 
## 13 Mystery      67533021.  39218750 
## 14 Romance      31264848.  25107500 
## 15 Sci-Fi       29788371.  27607143.
## 16 Thriller         2468     300000 
## 17 Western      20821884    3465000</code></pre>
<pre class="r"><code>movies_3&lt;-mutate(movies,return_on_budget=gross/budget)
movies_3</code></pre>
<pre><code>## # A tibble: 2,961 x 12
##    title genre director  year duration  gross budget cast_facebook_l~  votes
##    &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;            &lt;dbl&gt;  &lt;dbl&gt;
##  1 Avat~ Acti~ James C~  2009      178 7.61e8 2.37e8             4834 8.86e5
##  2 Tita~ Drama James C~  1997      194 6.59e8 2.00e8            45223 7.93e5
##  3 Jura~ Acti~ Colin T~  2015      124 6.52e8 1.50e8             8458 4.18e5
##  4 The ~ Acti~ Joss Wh~  2012      173 6.23e8 2.20e8            87697 9.95e5
##  5 The ~ Acti~ Christo~  2008      152 5.33e8 1.85e8            57802 1.68e6
##  6 Star~ Acti~ George ~  1999      136 4.75e8 1.15e8            37723 5.35e5
##  7 Star~ Acti~ George ~  1977      125 4.61e8 1.10e7            13485 9.11e5
##  8 Aven~ Acti~ Joss Wh~  2015      141 4.59e8 2.50e8            92000 4.63e5
##  9 The ~ Acti~ Christo~  2012      164 4.48e8 2.50e8           106759 1.14e6
## 10 Shre~ Adve~ Andrew ~  2004       93 4.36e8 1.50e8             1148 3.15e5
## # ... with 2,951 more rows, and 3 more variables: reviews &lt;dbl&gt;, rating &lt;dbl&gt;,
## #   return_on_budget &lt;dbl&gt;</code></pre>
<pre class="r"><code>movies_4&lt;-movies_3%&gt;%
group_by(genre)%&gt;%
summarise(avg_return_on_budget=mean(return_on_budget))
arrange(movies_4,desc(avg_return_on_budget))</code></pre>
<pre><code>## # A tibble: 17 x 2
##    genre       avg_return_on_budget
##    &lt;chr&gt;                      &lt;dbl&gt;
##  1 Horror                  88.3    
##  2 Biography               22.3    
##  3 Musical                 18.8    
##  4 Family                  14.1    
##  5 Documentary              8.70   
##  6 Western                  7.06   
##  7 Fantasy                  6.68   
##  8 Animation                5.01   
##  9 Comedy                   3.71   
## 10 Mystery                  3.27   
## 11 Romance                  3.17   
## 12 Drama                    2.95   
## 13 Adventure                2.41   
## 14 Crime                    2.17   
## 15 Action                   1.92   
## 16 Sci-Fi                   1.58   
## 17 Thriller                 0.00823</code></pre>
<ul>
<li>Produce a table that shows the top 15 directors who have created the highest gross revenue in the box office. Don’t just show the total gross amount, but also the mean, median, and standard deviation per director.</li>
</ul>
<pre class="r"><code>movies &lt;- read_csv(here::here(&quot;data&quot;, &quot;movies.csv&quot;))
movies_5&lt;-movies_3%&gt;%
group_by(director)%&gt;%
summarise(total_gross=sum(gross),avg_gross=mean(gross),
med_gross=median(gross),sd_gross=sd(gross))
movies_6&lt;-arrange(movies_5,desc(total_gross))
head(movies_6,n=15)</code></pre>
<pre><code>## # A tibble: 15 x 5
##    director          total_gross  avg_gross  med_gross   sd_gross
##    &lt;chr&gt;                   &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
##  1 Steven Spielberg   4014061704 174524422. 164435221  101421051.
##  2 Michael Bay        2231242537 171634041. 138396624  127161579.
##  3 Tim Burton         2071275480 129454718.  76519172  108726924.
##  4 Sam Raimi          2014600898 201460090. 234903076  162126632.
##  5 James Cameron      1909725910 318287652. 175562880. 309171337.
##  6 Christopher Nolan  1813227576 226653447  196667606. 187224133.
##  7 George Lucas       1741418480 348283696  380262555  146193880.
##  8 Robert Zemeckis    1619309108 124562239. 100853835   91300279.
##  9 Clint Eastwood     1378321100  72543216.  46700000   75487408.
## 10 Francis Lawrence   1358501971 271700394. 281666058  135437020.
## 11 Ron Howard         1335988092 111332341  101587923   81933761.
## 12 Gore Verbinski     1329600995 189942999. 123207194  154473822.
## 13 Andrew Adamson     1137446920 284361730  279680930. 120895765.
## 14 Shawn Levy         1129750988 102704635.  85463309   65484773.
## 15 Ridley Scott       1128857598  80632686.  47775715   68812285.</code></pre>
<ul>
<li>Finally, ratings. Produce a table that describes how ratings are distributed by genre. We don’t want just the mean, but also, min, max, median, SD and some kind of a histogram or density graph that visually shows how ratings are distributed.</li>
</ul>
<pre class="r"><code>movies &lt;- read_csv(here::here(&quot;data&quot;, &quot;movies.csv&quot;))
movies_7&lt;-movies_3%&gt;%
group_by(genre)%&gt;%
summarise(mean_rating=mean(rating),min_rating=min(rating),
max_rating=max(rating),med_rating=median(rating),
sd_rating=sd(rating))
movies_7</code></pre>
<pre><code>## # A tibble: 17 x 6
##    genre       mean_rating min_rating max_rating med_rating sd_rating
##    &lt;chr&gt;             &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
##  1 Action             6.23        2.1        9         6.3      1.03 
##  2 Adventure          6.51        2.3        8.6       6.6      1.09 
##  3 Animation          6.65        4.5        8         6.9      0.968
##  4 Biography          7.11        4.5        8.9       7.2      0.760
##  5 Comedy             6.11        1.9        8.8       6.2      1.02 
##  6 Crime              6.92        4.8        9.3       6.9      0.849
##  7 Documentary        6.66        1.6        8.5       7.4      1.77 
##  8 Drama              6.73        2.1        8.8       6.8      0.917
##  9 Family             6.5         5.7        7.9       5.9      1.22 
## 10 Fantasy            6.15        4.3        7.9       6.45     0.959
## 11 Horror             5.83        3.6        8.5       5.9      1.01 
## 12 Musical            6.75        6.3        7.2       6.75     0.636
## 13 Mystery            6.86        4.6        8.5       6.9      0.882
## 14 Romance            6.65        6.2        7.1       6.65     0.636
## 15 Sci-Fi             6.66        5          8.2       6.4      1.09 
## 16 Thriller           4.8         4.8        4.8       4.8     NA    
## 17 Western            5.70        4.1        7.3       5.70     2.26</code></pre>
<pre class="r"><code>ggplot(movies_3,aes(y=rating))+
geom_boxplot()+facet_wrap(~genre)+labs(title=&quot;the Histogram Distribution of Ratings for Genres&quot;,
x=&quot;the ratings for each genre&quot;)</code></pre>
<p><img src="/projects/project2_files/figure-html/ratings-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="use-ggplot-to-answer-the-following" class="section level2">
<h2>Use <code>ggplot</code> to answer the following</h2>
<ul>
<li>Examine the relationship between <code>gross</code> and <code>cast_facebook_likes</code>. Produce a scatterplot and write one sentence discussing whether the number of facebook likes that the cast has received is likely to be a good predictor of how much money a movie will make at the box office. What variable are you going to map to the Y- and X- axes?</li>
</ul>
<pre class="r"><code>plot1&lt;- ggplot(data = movies_3, 
mapping = aes(x = cast_facebook_likes, y = gross))+
geom_point() +geom_smooth(se = FALSE)+scale_x_log10() +
labs(title = &quot;Relationship between the Number of Facebook Likes and Gross Earnings &quot;,
x = &quot;the number of facebook likes &quot;,y = &quot;gross earnings in the box office&quot;) +NULL
plot1</code></pre>
<p><img src="/projects/project2_files/figure-html/gross_on_fblikes-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>According to the upward slope of the plot, there is a positive correlation between the number of facebook likes and the money a movie will make at the box office, so the number of facebook likes that the cast has received is likely to be a good predictor of the money a movie will make at the box office. I am going to map the number of facebook likes to the X- axis, and the gross earnings in the box office to the Y- axis.</p>
</blockquote>
<ul>
<li>Examine the relationship between <code>gross</code> and <code>budget</code>. Produce a scatterplot and write one sentence discussing whether budget is likely to be a good predictor of how much money a movie will make at the box office.</li>
</ul>
<pre class="r"><code>plot2&lt;- ggplot(data = movies_3, mapping = aes(x = budget, y = gross))+
geom_point() +geom_smooth(se = FALSE)+scale_x_log10()+
labs(title = &quot;Relationship between Budget and Gross Earnings &quot;,
x = &quot;budget&quot; ,y = &quot;gross earnings in the box office&quot;) +NULL
plot2</code></pre>
<p><img src="/projects/project2_files/figure-html/gross_on_budget-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>According to the upward slope of the plot, there is a positive correlation between budget and the money a movie will make at the box office, so budget is likely to be a good predictor of the money a movie will make.</p>
</blockquote>
<ul>
<li>Examine the relationship between <code>gross</code> and <code>rating</code>. Produce a scatterplot, faceted by <code>genre</code> and discuss whether IMDB ratings are likely to be a good predictor of how much money a movie will make at the box office. Is there anything strange in this dataset?</li>
</ul>
<pre class="r"><code>plot3&lt;- ggplot(data = movies_3, mapping = aes(x = rating, y = gross))+
geom_point() +geom_smooth(se = FALSE)+facet_wrap(~genre)+
labs(title = &quot;Relationship between Ratings and Gross Earnings &quot;,
x = &quot;ratings&quot; ,y = &quot;gross earnings in the box office&quot;) +NULL
plot3</code></pre>
<p><img src="/projects/project2_files/figure-html/gross_on_rating-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>For some genres such as action, adventure and comedy, the slopes of the plots are upward sloping. For some genres such as drama, fantasy and horror, the slopes are relatively flat. For some genres such as mystery and Sci-Fi,there is a fluctuation. And for documentary, the slope is even downward sloping, suggesting a negative correlation between ratings and gross earnings in the box office. This is the phenomenon that is strange in this dataset. Therefore, IMDB ratings are not likely to be a good predictor of the money a movie will make at the box office.</p>
</blockquote>
</div>
</div>

                        </div>
                    </section>
            <!-- Disqus Inject -->
                
            </div>
            
        <!-- Footer -->
            
                <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <ul class="icons">
                
                    <li><a href="https://twitter.com/pB4yxUSTwqc4p8P" class="icon alt fa-twitter" target="_blank"><span class="label">Twitter</span></a></li>
                
                    <li><a href="https://www.facebook.com/pingchuan.tian.5" class="icon alt fa-facebook" target="_blank"><span class="label">Facebook</span></a></li>
                
                    <li><a href="https://github.com/Pingchuan-Tian" class="icon alt fa-github" target="_blank"><span class="label">GitHub</span></a></li>
                
            </ul>
            <ul class="copyright">
                <li>&copy; Company Name</li>
                
                <li>Design:  <a href="https://www.html5up.net">HTML5 UP</a></li>
                
            </ul>
        </div>
    </footer>

            
        </div>

    <!-- Scripts -->
        <!-- Scripts -->
    <!-- jQuery -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/jquery.scrolly.min.js"></script>
    <script src="/js/jquery.scrollex.min.js"></script>
    <script src="/js/skel.min.js"></script>
    <script src="/js/util.js"></script>

    

    <!-- Main JS -->
    <script src="/js/main.js"></script>

    

    

    </body>
</html>
